### ISSUE TITLE
How can i read the raw data of jpeg without header to get mcu value to generator the width and height from raw data

### ISSUE THREAD

**Issue by HanalogInstruments** [BitMiracle/libjpeg.net#10]
Hi,

Could you give me example code of read mcu from raw data of jpeg without header only raw data after FFDA+12 bytes, because i have rebuild header for corrupted jpeg from sample jpeg have same chroma sampling, but i want to know decode the raw data of corupted jpeg to get width and height value from mcu to patch for the SOF of good header file, thank you!

Best regards,
Hanalog Inc

**Comment by Bobrovsky** [comment]
This is a question for StackOverflow or another similar site.
