### ISSUE TITLE
SoftwareBitmap to 

### ISSUE THREAD

**Issue by koolzz** [BitMiracle/libjpeg.net#4]
Hi,

I'm trying to convert a SoftwareBitmap into a JpegImage. SoftwareBitmap is obtainted from camera data of the HoloLens. 

I was getting a error from this piece of code:
```
private async void Send_bytes_bitmap(SoftwareBitmap frameBitmap) {
            ... 

            WriteableBitmap wrbitmap = new WriteableBitmap(frameBitmap.PixelWidth, frameBitmap.PixelHeight);
            frameBitmap.CopyToBuffer(wrbitmap.PixelBuffer);

            NetworkStream stream = new NetworkStream(sender);

            // This line gives an error
            JpegImage q = new JpegImage(wrbitmap);  

            ...
}
```

Is there a better/simpler way of doing this? Would appreciate your help, sorry if its a dump question this is my first experience with c# and Microsoft APIs.

**Comment by Bobrovsky** [comment]
Hello,

What error do you get?
