### ISSUE TITLE
Cross target .NETSTANDARD2.0

### ISSUE THREAD

**Issue by iamcarbon** [BitMiracle/libjpeg.net#5]
Microsoft recommends cross targeting .NETStandard 1.x libraries to .NETStandard 2.0 to simplify the dependency graphs. This avoids pulling in 50+ dlls on modern runtimes. Can we get a .NETSTANDARD 2.0 target for this library?

**Comment by Bobrovsky** [comment]
Jason,

When you build the library, you should get two versions: one for .NET Standard 1.6 and one for 2.0.
The NuGet also contains two versions. 

Does it help? If no, then please clarify your workflow and the issue.
